Remove Lint/Syntax (cannot disable)
See https://docs.rubocop.org/rubocop/configuration.html#generic-configuration-parameters

```
$ rubocop -c config/disable_all.yml --show-cops
Error: configuration for Syntax cop found in config/disable_all.yml
It's not possible to disable this cop.
```

It's re-enabled in chefstyle.yml anyhow

Confirmed no change in cop configuration
```
$ ./bin/chefstyle --show-cops | sha256sum
faa8fd05273862f47447a5357b8001976e8badb8d53c4e761f046383396930b5  -
```

Signed-off-by: David Crosby <dcrosby@fb.com>